[project]
name = "olo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.1",
    "environs>=14.5.0",
    "whitenoise>=6.11.0",
]
